#!/bin/sh

CONF="/data/etc/mosquitto.conf"

start() {
	printf "Starting mosquitto...\n"
	/usr/sbin/mosquitto -c ${CONF} -d
}
stop() {
	printf "Stopping mosquitto...\n"
	kill $(cat /var/run/mosquitto.pid)
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
